- name: Create nginx yum repo
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: false

- name: Install nginx
  yum: name=nginx state=latest

- name: Remove default server config
  file: state=absent path=/etc/nginx/conf.d/default.conf

- name: Install libsemanage-python to be able to run seboolean module
  yum: name=libsemanage-python state=installed

- name: Set SELinux httpd flags
  seboolean: name={{ item }} state=yes persistent=yes
  with_items:
    - httpd_can_network_connect

- name: Configure nginx service
  service:
    name: nginx
    state: started
    enabled: true
