---
- name: Delete compute instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Delete instances
    gce:
      instance_names: ghost-app
      state: deleted
      zone: "{{ zone }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
    register: app_servers

  - name: Delete DNS 'A' record for blog2.teadd.uk
    gcdns_record:
      state: absent
      zone: teadd.uk.
      type: A
      record: blog2.teadd.uk
      credentials_file: "{{ credentials_file }}"
      service_account_email: "{{ service_account_email }}"
      project_id: "{{ project_id }}"
      overwrite: true

  - name: Delete firewall rules
    gce_net:
      state: absent
      name: default
      fwname: mb-ghost-app-http
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: Delete swap disk
    gce_pd:
      state: deleted
      name: ghost-swap
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
