- name: Create compute instance(s)
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    service_account_email: teadd-provision@teadd-blog.iam.gserviceaccount.com
    credentials_file: /Users/michael/Develop/ghost-blog/pkey.pem
    project_id: teadd-blog
    machine_type: f1-micro
    image: centos-7
    zone: europe-west1-b
  
  tasks:
#    - name: Launch instances
#      gce:
#        instance_names: ghost-app
#        machine_type: "{{ machine_type }}"
#        image: "{{ image }}"
#        zone: "{{ zone }}"
#        service_account_email: "{{ service_account_email }}"
#        pem_file: "{{ credentials_file }}"
#        project_id: "{{ project_id }}"
#      register: app_servers
#    - debug:
#        var: app_servers

    - name: Define DNS zone for teadd.uk
      gc_dns_zone:
        domain: teadd.uk.
        name: teadd-uk
        ttl: 86400
        description: teadd.uk
        service_account_email: "{{ service_account_email }}"
        pem_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
