- fail: msg="Variable '{{ item }}' is undefined"
  when: "{{ item }} is undefined"
  with_items:
    - device

- name: Check if a device is already defined as swap
  command: blkid -l -t TYPE=swap -o device
  ignore_errors: true
  register: blkid_result
  changed_when: false

- name: Make swap partion on {{ device }}
  command: mkswap {{ device }}
  when: blkid_result.rc != 0

- name: Add swap device to fstab
  mount:
    state: present
    src: "{{ device }}"
    name: none
    fstype: swap

- name: Enable swap
  command: swapon -a
