- name: Create directory for LetsEncrypt stuff
  file:
    state: directory
    path: /etc/letsencrypt
    mode: 0700

- name: define certbot config file
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini

- name: Install nginx http server config
  template:
    src: http.nginx.conf.j2
    dest: /etc/nginx/conf.d/http.conf

- name: Force nginx to reload now
  service: name=nginx state=reloaded

- name: run certbot
  command: /usr/bin/certbot certonly --noninteractive

- name: Generate Strong Diffie-Hellman Group
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048
  args:
    creates: /etc/ssl/dhparam.pem

- name: Install nginx ssl server config
  template:
    src: https.nginx.conf.j2
    dest: /etc/nginx/conf.d/https.conf

- name: Force ngnix to reload again
  service: name=nginx state=reloaded

- name: configure automatic certificate renewal
  cron:
    name: certbot
    job: certbot renew --noninteractive
    hour: 3,15
