- name: Ensure packages installed
  yum: name="{{ item }}" state=installed
  with_items:
  - unzip
  - git

- name: Create ghost group
  group: name=ghost system=true

- name: Create ghost home folder
  file:
    state: directory
    path: "{{ ghost_install_dir }}"
    mode: 0755

- name: Create ghost user
  user: name=ghost group=ghost system=true home="{{ ghost_install_dir }}"

- name: Fix ghost home folder permissions
  file:
    state: directory
    path: "{{ ghost_install_dir }}"
    owner: ghost
    group: ghost
    mode: 0755

- name: Download Ghost
  unarchive:
    src: https://ghost.org/zip/ghost-{{ ghost_version }}.zip
    remote_src: true
    dest: "{{ ghost_install_dir }}"
    owner: ghost
    group: ghost
    mode: 0755
    creates: "{{ ghost_install_dir }}/index.js"

- name: Install sqlite3 from source
  command: npm install sqlite3 --build-from-source
  args:
    chdir: "{{ ghost_install_dir }}"
    creates: "{{ ghost_install_dir }}/node_modules/sqlite3/sqlite3.js"
  become: true
  become_user: ghost

- name: Install Ghost
  npm:
    path: "{{ ghost_install_dir }}"
    production: true
  become: true
  become_user: ghost

- name: Download themes
  git:
    repo: https://github.com/michaelbannister/odin.git
    dest: "{{ ghost_install_dir }}/content/themes/odin"
    version: master
  become: true
  become_user: ghost