- name: Install EPEL repo
  yum: name="epel-release" state=installed

- name: Ensure packages installed
  yum: name="{{ item }}" state=installed
  with_items:
  - unzip
  - git
  - libselinux-python
  - policycoreutils-python
  - certbot
